image: node:18

stages:
  - lint
  - test

eslint:
  stage: lint
  before_script:
    - npm install
  script:
    - npx eslint . --ext .jsx,.js
test:
  stage: test
  before_script:
    - npm install
  script:
    - npm test